server:
  port: 8099

spring:
  application:
    name: gateway-service

  cloud:
    config:
      uri: http://localhost:8888  # Dirección de tu Config Server

spring:
  cloud:
    gateway:
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**

        - id: course
          uri: http://localhost:8091
          predicates:
            - Path=/api/course/**

        - id: teacher
          uri: http://localhost:8092
          predicates:
            - Path=/api/teacher/**
