server:
  port: 8092

spring:
  application:
    name: msvc-teacher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsdb
    username: root
    password:

jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL8Dialect
