server:
  port: 8099

spring:
  application:
    name: gateway-service

  cloud:
    config:
      uri: http://localhost:8888  # Dirección de Config Server

    gateway:
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**

        - id: course
          uri: http://localhost:8091
          predicates:
            - Path=/api/course/**

        - id: teacher
          uri: http://localhost:8092
          predicates:
            - Path=/api/teacher/**

        - id: classroom
          uri: http://localhost:8093
          predicates:
            - Path=/api/classroom/**

        - id: sede
          uri: http://localhost:8094
          predicates:
            - Path=/api/sede/**
