server:
  port: 8099

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**  # ERROR

        - id: course
          uri: http://localhost:8091
          predicates:
            - Path=/api/course/**   # ERROR

        - id: teacher
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/teacher/**  # ERROR

        - id: classroom
          uri: http://localhost:8093
          predicates:
            - Path=/api/classroom/**  # ERROR

        - id: sede
          uri: http://localhost:8094
          predicates:
            - Path=/api/sede/**  # ERROR